name: Windows Premake Build

on:
  push:
    branches: [main, master, CI_CD]
  pull_request:
    branches: [main, master, CI_CD]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository + submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: List directory contents (debug)
      run: dir /s /b
      shell: cmd

    - name: Verify script exists (debug)
      run: |
        if exist scripts\setup\setup_windows.bat (
          echo Script exists
          type scripts\setup\setup_windows.bat
        ) else (
          echo Script not found
          dir scripts
          dir scripts\setup
        )
      shell: cmd

    - name: Run premake batch script
      run: scripts/setup/setup_windows.bat
      shell: cmd
      working-directory: ${{ github.workspace }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Debug x64
      run: msbuild /p:Configuration=Debug /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0 Luth.sln

    - name: Build Release x64
      run: msbuild /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0 Luth.sln
